### ISSUE TITLE
Missing Order information

### ISSUE THREAD

**Issue by Seatig** [Seatig/Changhong#11]
There are still quite some fields on the Order screen shots that are not marked so please mark them and provide the corresponding direction in the property file. 

需要包含云账房里边所有跟订单相关的界面截屏及其上的字节段和定义。

**Comment by fahey520** [comment]
回复：目前长虹的系统上 就只有我们两张截图与订单相关，需要等到周一 和长虹那边确认一下，其它相关的就是主数据了。

**Comment by Seatig** [comment]
1. 现在的订单的页面上有好几个地方没有勾画，没有定义，请补齐。（这是我这个Issue里边的英文部分的要求）
2. 订单除了这个总结页面外，还有订单的详情页面，上次徐经理展示过的。请把详情页面定义了。
