### ISSUE TITLE
Missing MDS elements

### ISSUE THREAD

**Issue by Seatig** [Seatig/Changhong#23]
1.  四川省政府非税收入通用票据, 合计金额小写：
![image](https://cloud.githubusercontent.com/assets/27685494/26733819/03b20440-478a-11e7-9285-30920eb9283c.png)

2. _电子同城来账业务， 单位名字
![image](https://cloud.githubusercontent.com/assets/27685494/26742524/04c138e8-47ac-11e7-818c-ebf85ff2993c.png)

金额小写，这个最重要了‘
![image](https://cloud.githubusercontent.com/assets/27685494/26742603/68204a6e-47ac-11e7-8efb-ade609820384.png)

章 
![image](https://cloud.githubusercontent.com/assets/27685494/26742618/75e62876-47ac-11e7-9993-8da9798b0e0c.png)

3. 社会保险费专用票据： 纠正repeating information 排列顺序

章： 
![image](https://cloud.githubusercontent.com/assets/27685494/26745164/45f8f728-47b7-11e7-9cd1-09e0a357572b.png)

4. 非经营性结算统一票据： 
监制章 
![image](https://cloud.githubusercontent.com/assets/27685494/26745186/64276ab8-47b7-11e7-8388-5f41457b9965.png)

财务专用章 
![image](https://cloud.githubusercontent.com/assets/27685494/26745213/7fa88f1a-47b7-11e7-988d-169073c2f6f2.png)

**Comment by fahey520** [comment]
ok  我先把余下的改完，后面再第二次复查时 再修改

**Comment by Seatig** [comment]
这样不好。查到的问题要先改了，包括前面上一次我提到的问题。后面就全部忘记了。我们先把这些问题改好了，再往前走。这样才能是一步一个脚印，把事情做扎实。

**Comment by fahey520** [comment]
好的，我就是怕把自己改晕了

**Comment by fahey520** [comment]
文件夹: MDS-Checked中的MDS check table 文件 有修改进度。

**Comment by fahey520** [comment]
已经修改
