### ISSUE TITLE
Problems to be fixed

### ISSUE THREAD

**Issue by Seatig** [Seatig/Changhong#25]
Problems need to be fixed: 

Deposit Account Interest Claim. 

1. The diagram is missing boxes and element reference numbers for the title and the 3 elements of the seal. 

2. There are 12 elements identified on the diagram, but only 9 have reference numbers specified in the Master, so 3 plus the missing 4 don’t seem to exist in the master MDS model. 

3. Of those 9 elements included in the Master, none of them have a Chinese or English draft definition, 

4. none have an English (Google) translation of the Properties file description, 

5. five columns of content that are simply repeating formulas to drag down are incomplete. 

6. And from the perspective of selecting semantic labels, none of the proposed names express complete semantic information. (Note: Only the Semantic Label Base column should contain text. The "Full Semantic Standard Label" column is calculated by formula and will contain a value based on the "Semantic Label Base" column.)

7. Several of the elements are duplicates of existing elements and will need to be merged or removed 

8. and none of the enumerated or code elements were given the correct type. 

9. Elements were also not placed in the correct model containers, so I need to reorder the elements.
E.g. Date elements not placed under the Document Dates Attributes heading.

10. And example values were not correct. E.g. the example date/time value did not include a time. (This might be because the element was identified as a date, even though the document example image clearly shows it is a date/time.)

11. Answer all the questions in Column AI in Master MDS

12. If the mini-MDS has already been merged into Master, we don't correct the problems in mini-MDS but instead directly in the master.

**Comment by TimothyRan** [comment]
I updated the item #6 to indicate that we don't want to hand edit column K. The Full Semantic Label is created from the Semantic Label Base.
