### ISSUE TITLE
On converter converted classification standards(关于转换器转换后的分类标准)

### ISSUE THREAD

**Issue by michelle520** [Seatig/Changhong#32]
through the converter after conversion, I think should contain all the MDS corresponding classification standard, but the result is only Taxonomy (Delivery 1.0) files in a few, I think everyone in merging the Master of time, the lack of an association. Will only appear a few classification standard. Hope to get answer.
(通过转换器转换后，我认为应该包含全部的MDS对应的分类标准，但结果只有(Delivery 1.0 Taxonomy)文件里的几个，我认为是大家在合并Master的时候，缺少了某种关联。才会只出现几个分类标准。希望得到回答。)

**Comment by michelle520** [comment]
Reference directory: Task 2 Deliverables \ \ Delivery 1.0 Taxonomy

**Comment by fahey520** [comment]
I'm sorry, I use michelle's accounts

**Comment by Seatig** [comment]
Taxonomy exists in combined form.
