### ISSUE TITLE
Questions about gen-XDC-XBRL.bat use

### ISSUE THREAD

**Issue by Glenn-520** [Seatig/Changhong#41]
Changhong's colleagues reported a few lines of error messages when using gen-XDC-XBRL.bat:
1. [IOerror] changhong-XDC_parts_v0.1.1_2017-06-15.xsd: file error: [Errno 2] No su
Ch file or directory: 'changhong-XDC_parts_v0.1.1_2017-06-15.xsd' - XDC_core_v0.
1.1_2017-06-15.xsd
2. [IOerror] changhong-XDC_parts_v0.1.1_2017-06-15.xsd: file error: [Errno 2] No su
Ch file or directory: 'G: \\ Changhong \\ XDC \\ Delivery 1.0 \\ Transformer \\ XDC_v0.1.1 \\ cha
Nghong-XDC_parts_v0.1.1_2017-06-15.xsd '- XDC_core_v0.1.1_2017-06-15.xsd 387

The complete error message is displayed in the attachment。
[gen-XDC-XBRL-v0.1.1-errout.txt](https://github.com/Seatig/Changhong/files/1121507/gen-XDC-XBRL-v0.1.1-errout.txt)

**Comment by TimothyRan** [comment]
These messages were indicating that we were missing the XBRL support schema files that specify reference linkbases where some of the Document Model metadata is represented. We have these files now and are making additions as we gather the metadata that will be stored in the reference linkbases. I have uploaded the files to GitHub in the Delivery 1.1 directory.
