### ISSUE TITLE
to Timo thy

### ISSUE THREAD

**Issue by fahey520** [Seatig/Changhong#6]
Hello Timo thy help me to look at in the MDS:"Gernal Written Fapiao_通用手开发票_fahey_20170502"Whether it is right.
and  Please answer a few questions:
1.About Fapiao Properties Row # : If this field existed in Fapiao, but did not store in the Financial DataCloud, how to mark up the number?

2.Does that Document Template Category mean the full name of company which printed the Fapiao?

3.What is the difference between Document Template Production Id and Document Template Producer Entity Id?

4.Does that Document Designated Entity Name mean the full name of document(ex: Gernal Written Fapiao of Chengdu,Sichuan)?

5.Description - External Reference Document Name? what mean?

Thank you!!

**Comment by TimothyRan** [comment]
Hello Fahey. My responses are below.

1. The Fapiao Properties row is the row number of the Fapiao Properties document that we are using to determine ChangHong element requirements. If we determine that an element should exist, but it is not identified in the Fapiao Properties document, then we should capture the row number as "na" for not available.

2. The Document Template Category element is a way for us to capture the category of the document model we are creating. We have not yet created our final list of the values that can be used to identify the various document template categories. We will create this list later. In the meantime, the element will be present in every model to carry the metadata.

3. Document Template producers will provide an Id number to identify the template. The government provides an id number to identify the producer. We can rename this as a Producer Entity Tax Id.

4. If the Document has an Entity Name pre-printed on the templates before they are filled in with data, then we will record the name as it means the document template is designated to be used by only one entity.

5. The name of the document from which we are getting the reference definition information, i.e. Fapiao Properties 子类型字段 02 - 20170417-Wei.xlsx
